### ISSUE TITLE
secp256k1 module error

### ISSUE THREAD

**Issue by jesuasir007** [yuzushioh/EthereumKit#89] opened 2018-04-24 06:12 UTC
ya , ethereumkit installation is completed , i have add an ethereumkit module its shows some error,please check me .Missing required module 'secp256k1'

**Comment by yuzushioh** [comment] 2018-04-24 06:27
Thank you for the report. I will investigate it. I might know the cause.

**Comment by panjiulong** [comment] 2018-04-25 08:10
I have same problem

**Comment by Dubickiy** [comment] 2018-04-27 09:05
+ So do I

**Comment by yuzushioh** [comment] 2018-05-06 08:08
@jesuasir007 @panjiulong I released 1.1.0. could you try updating?

**Comment by maximuskravchenko** [comment] 2018-05-11 13:52
Hi, I had a problem with secp256k1.
With 1.1.0 there is another problem:

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/admin/Projects/TESTS/CarthTest/Carthage/Checkouts/EthereumKit/EthereumKit.xcodeproj -scheme EthereumKit -configuration Release -derivedDataPath /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/EthereumKit/1.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/7p/9xj8x2dd1qqczd51zlxvgq_w0000gn/T/EthereumKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/admin/Projects/TESTS/CarthTest/Carthage/Checkouts/EthereumKit)

**Comment by yuzushioh** [comment] 2018-05-18 11:56
related to #106

**Comment by yuzushioh** [comment] 2018-05-25 07:44
I managed to fix this problem. I will patch it over this weekend. Thank you!

**Comment by yuzushioh** [comment] 2018-05-26 05:43
this has been fixed in version 1.2.0

**Closed by yuzushioh** 2018-05-26 05:43 UTC

**Comment by dujinxin** [comment] 2018-05-27 08:52
This problem still exists in version 1.2.0,help me !!!

**Comment by yuzushioh** [comment] 2018-05-27 11:48
@dujinxin clean up everything such as carthage cache or build cache

**Comment by dujinxin** [comment] 2018-05-28 04:01
@yuzushioh I have tried various ways to solve this problem，and solved this problem by MrShafiee's method, thanks! @MrShafiee
